### ISSUE TITLE
How to configure alternate link for GHC tarball?

### ISSUE THREAD

**Issue by hasufell** [haskell/ghcup-hs#100]
In GitLab by @trac-runeks on Nov 16, 2020, 18:24

Hi,

I'm trying to install GHC 8.8.3 on my machine, but https://downloads.haskell.org barely works. The speed starts at 20-30 KB/s, and eventually stalls completely:

```
$ ghcup install ghc 8.8.3
[ Warn  ] New GHCup version available: 0.1.11. To upgrade, run 'ghcup upgrade'
[ Info  ] downloading: https://downloads.haskell.org/~ghc/8.8.3/ghc-8.8.3-x86_64-apple-darwin.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 49  181M   49 90.2M    0     0  28811      0  1:49:59  0:54:45  0:55:14     0^C
```

The [example config (under **Example 2**)](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/master/config.yaml#L43) contains an example for specifying a custom download link, but I can't figure out what I need to set the various keys to in order to install `ghc-8.8.3-x86_64-apple-darwin`.

My current attempts looks like the following, which doesn't work. 

```yaml
url-source:
  ## Use the internal download uri, this is the default
  # GHCupURL: []

  ## Example 2: Add custom tarballs to the default downloads, overwriting duplicate versions
  AddSource:
    Left:
      toolRequirements: {} # this is ignored
      ghcupDownloads:
        GHC:
          8.8.3:
            viTags: []
            viArch:
              A_64:
                Darwin:
                  unknown_versioning:
                    dlUri: https://distfiles.macports.org/ghc/ghc-8.8.3-x86_64-apple-darwin.tar.xz
                    dlSubdir: ghc-8.8.3
                    dlHash: 7016de90dd226b06fc79d0759c5d4c83c2ab01d8c678905442c28bd948dbb782
```

Any help would be appreciated.
