### ISSUE TITLE
Vim-like keybindings and Escape in TUI

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/ghcup-hs#1098]
Would it be possible to support `k` and `j` for `Up` and `Down` in the TUI? Additionally, `l` would work great for `Set` (or `Install` but I think `Set` makes more sense as a more frequently used option, presumably). There could be an opt-in setting for it, but these keys are not used anyway, so the only potential issue is that we could steal them from some future commands. But when I think about cost/benefit, I think using these globally, without a setting, would work best.

Not really Vim-like but while we're on the topic of keybindings: could you support `Esc` for quitting, both from the program and from the pop-up menus that were just released with 0.1.30? Ctrl-C for quitting popups is what I find the most annoying in this UX. But quitting altogether with `Esc` is also something, I'm sure, many people are used to. These two ideas work great together: you could easily quit from a popup and then from the program by consequently hitting `Esc`!

**Comment by hasufell** [comment]
You can already configure all keys.

https://github.com/haskell/ghcup-hs/blob/master/data/config.yaml#L16

**Comment by ulysses4ever** [comment]
Thank you for the pointer! That should work. I still think it'd be an improvement to UX if the particular settings I mentioned were in place by default.

**Comment by hasufell** [comment]
> I still think it'd be an improvement to UX if the particular settings I mentioned were in place by default.

I don't think I want to get into editor wars :)

**Comment by ulysses4ever** [comment]
Fair enough. Trying this now, anc changes to `~/.ghcup/config` don't seem to be picked up by the tool on restart. Any ideas why that may be the case?

**Comment by hasufell** [comment]
Did you see https://www.haskell.org/ghcup/guide/#configuration

**Comment by ulysses4ever** [comment]
I did not but it doesn't say why configuration cchanges may not be picked up. Am I missing something?

**Comment by hasufell** [comment]
The file is `~/.ghcup/config.yaml`?

**Comment by ulysses4ever** [comment]
Sorry, I forgot the `.yaml` above, but yes, this one. It's current content is:
```yaml
key-bindings:
  up:
    KChar: 'k'
cache: null
downloader: Curl
gpg-setting: null
keep-dirs: null
key-bindings: null
meta-cache: null
meta-mode: null
mirrors: null
no-network: null
no-verify: null
platform-override: null
url-source:
- GHCupURL
- https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml
- https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.8.yaml
verbose: null
```
I added the first key `key-binddings`, and all the rest was there. I tried running with `-v`: it showed some stuff about metadata files but nothing about loading the config. Perhaps it should?

**Comment by hasufell** [comment]
Looks like a regression: https://github.com/haskell/ghcup-hs/issues/1099

**Comment by dfordivam** [comment]
@ulysses4ever  It took me a while to figure the issue here, you need to remove the `key-bindings: null`. Though I am doing more testing to confirm if there is any regression.

**Comment by hasufell** [comment]
Oh dear 😄

**Comment by ulysses4ever** [comment]
Oh, so embarrassing! Thank you guys!

I have another question / feature request: is it possible to support several keys for one action? Say, I want to be able to go up in the list via `k` or the `Up` key. I tried
```
key-bindings:
  up:
    { KChar: 'k', KUp: [] }
```
```
key-bindings:
  up:
    - KChar: 'k'
    - KUp: []
```
but in both cases the last binding seems to override the first. Should I open a feature-request ticket?
