### ISSUE TITLE
Termux/Android platform support. 

### ISSUE THREAD

**Issue by dhuux** [haskell/ghcup-hs#938]
now with help of `glibc for termux` project we can run most of linux `AArch64 binaries` on Termux. no need for them to be linked against the `bionic libc` to work on Termux. i hope you to support termux as a distribution. i can still setup these tools manually but i would like to use `ghcup` for that.

![Screenshot_20231121-221207_Termux](https://github.com/haskell/ghcup-hs/assets/63465816/17baf95c-7d86-4585-a97e-9f46718cde99)

thanks.

**Comment by dhuux** [comment]
from the guide i found out that i can modify the distro detection with the `config.yaml` file. but how do i tell it to fetch the Linux aarch64 tarball instead of the x86_64 one? 

![Screenshot_20231122-011304_Termux](https://github.com/haskell/ghcup-hs/assets/63465816/38305f9c-e1c4-4486-8ad5-e51e69954fc7)

**Comment by hasufell** [comment]
```
platform-override:
  arch: A_ARM64
  platform:
    contents: Ubuntu
    tag: Linux
  version: '18.04'
```
